postgres:
  image: postgres:13.1
  environment:
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: twinte_session_service
  ports:
    - 5432:5432
  volumes:
    - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
